### ISSUE TITLE
Use self-define dictionary

### ISSUE THREAD

**Issue by zhuzhikui** [icmpnorequest/NLP_Chinese_segging_tagging#2]
How can we use self-define dictionary to segment and pos tagger? Some word not in the pos training can't be identified and the segment result is awful.

**Comment by icmpnorequest** [comment]
@zhuzhikui 
Thank you so much for your comment. For the limitation of the `HMM + Viterbi` model and lack of training datasets, sometimes the segment result actually looks awful. We are glad to merge the code with self-defined dictionary if you could pull a request.
