### ISSUE TITLE
if i wanna train my own POS-tagging model, how to save my own training version?

### ISSUE THREAD

**Issue by marcusau** [icmpnorequest/NLP_Chinese_segging_tagging#3]
Thanks for your nice contribution. 

One more question,  I have built my own word segmentation model.

If i wanna build my own POS-tagger on the top of the segment results, by leveraging your tagger part, how to save the result in model.pkl  format, like these in your model?

Thanks a lot

**Comment by icmpnorequest** [comment]
@marcusau 
Thank you so much for your comment. According to your description, what I understood is that you wanna save your trained segging model in `model.pkl` format but you don't know how to save. I had no idea about how your model looks like. My mate implemented the segging model with `CRF` with `sklearn_crfsuite` in `CRF_Model.py` which you could refer to. 

Here is a pipeline about how to `save` and `load` model in `sklearn` with the `iris` dataset:
```
from sklearn import svm
from sklearn import datasets
from sklearn.externals import joblib

# 1. Create an model instance
clf = svm.SVC()

# 2. Load iris dataset
X, y = datasets.load_iris(return_X_y=True)

# 3. Fit data and label into SVC classifier
clf.fit(X, y)

# 4. Save the trained model with joblib.dump(classifier, filename)
joblib.dump(clf, "iris_svc.pkl")

# 5. Load the trained model with joblib.load(filename)
clf2 = joblib.load("iris_svc.pkl")

# 6. Prediction
print(clf2.predict(X[0:1]))
```

With `joblib` in `sklearn`, you could easily save and load your own model.
